permalink: /:categories/:title/
markdown: kramdown
exclude: 
 - "/scripts"

defaults:
  - 
    scope:
      path: ""
    values:
      author: "Eric Zillinger"

  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      is_post: true

